diversinet_sources = [
    'Data/Reader/Newick/NewickParser.cpp',
    'Data/Reader/Newick/TreeNode.cpp',
    'Data/Structure/Edge.cpp',
    'Data/Structure/Network.cpp',
    'Data/Structure/Node.cpp',
    'Interface/DiversinetInterface.cpp',
    'Likelihood/Approximator/BaseApproximator.cpp',
    'Likelihood/Approximator/BaseApproximator.h',
    'Likelihood/Approximator/DefaultApproximator.cpp',
    'Likelihood/Approximator/DefaultApproximator.h',
    'Likelihood/Approximator/Factory.cpp',
    'Likelihood/Integrators/AdaptiveIntegrators.hpp',
    'Likelihood/Integrators/CustomDenseRK.hpp',
    'Likelihood/Integrators/IntegratorFactory.hpp',
    'Likelihood/Kernels/CPU/EigenIntegrationKernel.cpp',
    'Likelihood/Kernels/CPU/EigenKernels.cpp',
    'Likelihood/Scheduler/BaseScheduler.cpp',
    'Likelihood/Scheduler/Event.cpp',
    'Likelihood/StateTypes/Utils.cpp',
    'Likelihood/StateTypes/Vector/EigenState.cpp',
    'Likelihood/StateTypes/Vector/EigenStateOperations.hpp',
    'Models/BaseModel.cpp',
    'Models/Factory.cpp',
    'Models/SimpleNetworkModel.cpp',
    'Parameters/Container.cpp',
    'Simulate/BaseSimulator.cpp',
    'Utils/MemoryPool/EigenCPU.cpp',
    'Utils/Output/OutputManager.cpp',
    'Utils/Parallel/Manager.cpp'
]

diversinet = shared_library('diversinet',
                             diversinet_sources,
                             include_directories : inc_for_lib,
                             dependencies : [eigen_dep, boost_dep_for_lib],
                             install : true)